# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: register-service
  labels:
    app: register-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: register-app
  type: ClusterIP